CC = gcc
MOUNT_DIR = .
BUILD_DIR = build

# Installation
PREFIX ?= /usr/local
BINDIR ?= $(PREFIX)/games/quake

# Flags
BASE_CFLAGS = -Dstricmp=strcasecmp -I$(MOUNT_DIR)
RELEASE_CFLAGS = $(BASE_CFLAGS) -g -O2 -ffast-math -funroll-loops -fomit-frame-pointer -fexpensive-optimizations
DEBUG_CFLAGS = $(BASE_CFLAGS) -g

CFLAGS ?= $(RELEASE_CFLAGS)

# Libraries
LDFLAGS = -lm

# SDL2
SDL_CFLAGS = `sdl2-config --cflags`
SDL_LDFLAGS = `sdl2-config --libs` -lm

# GLQuake
GL_LDFLAGS = -lGL -lX11 -lXext -ldl -lm
GL_CFLAGS = -DGLQUAKE -I/usr/include/GL

# Commands
DO_AS = $(CC) $(CFLAGS) -DELF -x assembler-with-cpp -o $@ -c $<

# Output directories
$(shell mkdir -p $(BUILD_DIR)/glquake $(BUILD_DIR)/sdl $(BUILD_DIR)/bin)

#############################################################################
# OBJECT LISTS
#############################################################################

# SDLQuake
SDL_OBJS_LIST = \
	cl_demo.o cl_input.o cl_main.o cl_parse.o cl_tent.o chase.o cmd.o \
	common.o console.o crc.o cvar.o draw.o d_edge.o d_fill.o d_init.o \
	d_modech.o d_part.o d_polyse.o d_scan.o d_sky.o d_sprite.o d_surf.o \
	d_vars.o d_zpoint.o host.o host_cmd.o keys.o menu.o mathlib.o model.o \
	net_dgrm.o net_loop.o net_main.o net_vcr.o net_udp.o net_bsd.o \
	pr_cmds.o pr_edict.o pr_exec.o r_aclip.o r_alias.o r_bsp.o \
	r_light.o r_draw.o r_efrag.o r_edge.o r_misc.o r_main.o r_sky.o \
	r_sprite.o r_surf.o r_part.o r_vars.o screen.o sbar.o sv_main.o \
	sv_phys.o sv_move.o sv_user.o zone.o view.o wad.o world.o cd_linux.o \
	sys_linux.o vid_sdl.o snd_dma.o snd_mem.o snd_mix.o snd_linux.o

# GLQuake
GL_OBJS_LIST = \
	cl_demo.o cl_input.o cl_main.o cl_parse.o cl_tent.o chase.o cmd.o \
	common.o console.o crc.o cvar.o \
	gl_draw.o gl_mesh.o gl_model.o gl_refrag.o gl_rlight.o gl_rmain.o \
	gl_rmisc.o gl_rsurf.o gl_screen.o gl_test.o gl_warp.o \
	host.o host_cmd.o keys.o menu.o mathlib.o net_dgrm.o net_loop.o \
	net_main.o net_vcr.o net_udp.o net_bsd.o pr_cmds.o pr_edict.o \
	pr_exec.o r_part.o sbar.o sv_main.o sv_phys.o sv_move.o sv_user.o \
	zone.o view.o wad.o world.o cd_linux.o sys_linux.o snd_dma.o \
	snd_mem.o snd_mix.o snd_linux.o gl_vidlinuxglx.o

# Build paths
SDL_OBJS = $(addprefix $(BUILD_DIR)/sdl/,$(SDL_OBJS_LIST)) 

GL_OBJS = $(addprefix $(BUILD_DIR)/glquake/,$(GL_OBJS_LIST)) 

#############################################################################
# TARGETS
#############################################################################

all: glquake sdlquake

glquake:   $(BUILD_DIR)/bin/glquake
sdlquake:  $(BUILD_DIR)/bin/sdlquake

# ==================== SDL2 TARGET ====================
$(BUILD_DIR)/bin/sdlquake: $(SDL_OBJS)
	@echo "Linking SDLQuake..."
	@$(CC) $(CFLAGS) -o $@ $(SDL_OBJS) $(SDL_LDFLAGS)

# ==================== GL TARGET ====================
$(BUILD_DIR)/bin/glquake: $(GL_OBJS)
	@echo "Linking GLQuake..."
	@$(CC) $(CFLAGS) -o $@ $(GL_OBJS) $(GL_LDFLAGS) $(LDFLAGS)

#############################################################################
# COMPILATION RULES
#############################################################################

# SDL2 rules
$(BUILD_DIR)/sdl/%.o: $(MOUNT_DIR)/%.c
	@echo "Compiling $< (SDL2)..."
	@$(CC) $(CFLAGS) $(SDL_CFLAGS) -o $@ -c $<

$(BUILD_DIR)/sdl/%.o: $(MOUNT_DIR)/%.s
	@echo "Assembling $< (SDL2)..."
	@$(DO_AS)

# GL rules
$(BUILD_DIR)/glquake/%.o: $(MOUNT_DIR)/%.c
	@echo "Compiling $< (GL)..."
	@$(CC) $(CFLAGS) $(GL_CFLAGS) -o $@ -c $<

$(BUILD_DIR)/glquake/%.o: $(MOUNT_DIR)/%.s
	@$(DO_AS)

#############################################################################
# INSTALL & HELP
#############################################################################

install: all
	@echo "Installing to $(DESTDIR)$(BINDIR)..."
	@mkdir -p $(DESTDIR)$(BINDIR)
	@cp $(BUILD_DIR)/bin/glquake   $(DESTDIR)$(BINDIR)/glquake
	@cp $(BUILD_DIR)/bin/sdlquake  $(DESTDIR)$(BINDIR)/sdlquake
	@chmod 755 $(DESTDIR)$(BINDIR)/glquake
	@chmod 755 $(DESTDIR)$(BINDIR)/sdlquake
	@echo "Done."

uninstall:
	@rm -f $(DESTDIR)$(BINDIR)/glquake
	@rm -f $(DESTDIR)$(BINDIR)/sdlquake
	@echo "Uninstalled."

help:
	@echo "Targets:"
	@echo "  make all        - Build glquake and sdlquake"
	@echo "  make sdlquake   - Build SDL2 software renderer"
	@echo "  make glquake    - Build OpenGL renderer"
	@echo "  make install    - Install all three"
	@echo "  make clean      - Clean build"

clean:
	rm -rf $(BUILD_DIR)